apiVersion: v1
kind: Pod
metadata:
  labels:
    app: share-pod
  name: share-pod
spec:
  volumes:
    - name: host-volume
      hostPath:
        path: /home/docker/pod-volume # path to the dir on the node
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: host-volume
  - image: debian
    name: debian
    volumeMounts:
    - mountPath: /host-vol
      name: host-volume
    command: ["/bin/sh", "-c", "echo Introduction to Kubernetes > /host-vol/index.html; sleep 3600"]